### ISSUE TITLE
実行するとエラーが出てturtlesimが動かせない

### ISSUE THREAD

**Issue by anmistu** [Kotakku/ros2-for-unity-android-package#1]
こんにちは
androidとunityの連携に関する環境構築をしていた際にエラーが出てしまいました。
実行しようとした際に出たエラーです
対処法を教えてほしいです。
os ubuntu22.04
ディストリビューション　humbule
ros2-for-unityの環境構築には成功しました。
![image](https://github.com/Kotakku/ros2-for-unity-android-package/assets/106851544/c83cdda2-ecd1-4dee-b704-e041fa77fa78)

**Comment by Kotakku** [comment]
```~/.profile```に```source /opt/ros/humble/setup.bash```が記述されているか確認してみてください
なければ追記した上でUbuntuを再起動してもう一度実行してみてください
自分の環境では記述されてないときに同じエラーが確認できました

**Comment by anmistu** [comment]
ありがとうございます。無事解決することができました。

**Comment by anmistu** [comment]
すみません、質問なのですがunityのエディターのバージョンは何を使用されてますか？
また、アンドロイドの設定をする際にホームページに描いたこと以外で必要なことがあれば教えていただきたいです
